<div class="order-type">
    <?php
    /**
     * @var Damian\OrderType\Block\Cart\OrderType $block
     */
    $orderTypes = $block->getOrderTypes();
    $first = true;
    ?>
    <strong for="order_type"><?=$block->getName().':';?></strong>
    <div class="options">
        <?php foreach ($orderTypes as $orderType): ?>
            <div class="option">
                <label>
                    <input type="radio" name="order_type" value="<?= $orderType->getId() ?>" <?php if ($first) {$first=false;echo 'checked';} ?>>
                    <?= $orderType->getTypeName() ?>
                </label>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Damian_OrderType/js/save_choice": {}
        }
    }
</script>